name: Run npx command

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: ~

on:
  push:
  workflow_dispatch:

jobs:
  run-npx:
    runs-on: ubuntu-latest
    steps:
      - run: npx -h
