name: Publish Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  release-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
          restore-keys: |
              ${{ runner.os }}-nimble-v2-
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: nimble -y install

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: ./github_actions_sandbox.exe
        if: runner.os == 'Windows'
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: ./github_actions_sandbox
        if: runner.os != 'Windows'

  release-publish:
    needs: release-build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - run: |-
          tar -zcvf Linux.tar.gz ./Linux
          zip -rv Windows.zip ./Windows
          zip -rv macOS.zip ./macOS

      - uses: softprops/action-gh-release@v2
        with:
          files: |-
              ./Linux.tar.gz
              ./Windows.zip
              ./macOS.zip
          generate_release_notes: true
