name: Publish Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}

      - uses: jiro4989/setup-nim-action@v1

      - run: nimble -y install

      - run: |-
          mkdir "$ASSET_DIR"
          cp ./github_actions_sandbox "./$ASSET_DIR"
          tar -zcf "$ASSET_FILE" "./$ASSET_DIR"
          echo "::set-output name=ASSET_FILE::$ASSET_FILE"
        env:
          ASSET_DIR: github-actions-sandbox
          ASSET_FILE: github-actions-sandbox.tar.gz
        id: asset

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.asset.outputs.ASSET_FILE }}
          generate_release_notes: true
