name: Run Sandbox

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-13

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-v2-
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: nim --eval:"echo defined(macosx); echo defined(osx); echo defined(linux); echo defined(unix); echo defined(cpu64); echo defined(amd64); echo defined(arm64)"

      - run: echo ${{ runner.name }}

      - name: Print runner info
        run: |
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
