name: Sandbox

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
              ${{ runner.os }}-nimble-
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: brew install libgtk gtk+3
        if: runner.os == 'macOS'
      - run: brew info gtk+3
        if: runner.os == 'macOS'
      - run: nimble -y install -d -p:-d:danger -p:-d:foo=1
        if: runner.os == 'Linux'
      - run: nimble -y install -p:"-d:danger" -p:"-d:foo=2"
        if: runner.os == 'Windows'
      - run: nimble -y install -d -p:-d:danger -p:-d:foo=3
        if: runner.os == 'macOS'
